### ISSUE TITLE
buttonLongPressed() not working as expected

### ISSUE THREAD

**Issue by jbobrow** [Move38/Blinks-Simulator#10]
Example, in mortals, we should see the display hold Green/Purple between 1.2 sec and 3 sec as a Blink is longPressed. Then switch to the team on the release of the button.

(note: it is possible this could be an issue with buttonDown or buttonReleased as well)

**Comment by xyfeng** [comment]
https://github.com/Move38/Blinks-Simulator/blob/6f3da5af5c818d7ea82dc707940ad46a201c3d7f/examples/js/blink.js#L202

I used flag for button events, once user checked the value, the flag get reset, I think that's the reason why. I can make the reset happen on the release event, what do you think? Also what is the 3 secs action? longlongpress? I didn't add that function, I thought it's for programming the blinks.

**Comment by xyfeng** [comment]
Update long pressed function, reset flags after button released.
