### ISSUE TITLE
array index beyond bounds produces weird behavior

### ISSUE THREAD

**Issue by gabrieljones** [Move38/Blinks-Simulator#16]
```C++
byte color = 0;

Color colors[8] = {RED,ORANGE,YELLOW,GREEN,CYAN,BLUE,MAGENTA,WHITE};

void setup() {
  color = random(8);
}

void loop() {
  setColor(colors[color]); 
}
```

![image](https://user-images.githubusercontent.com/18059585/102702338-aa1f3480-422f-11eb-8bf5-982d7548e770.png)

**Comment by gabrieljones** [comment]
I guess Arduino proper does not do bounds check either. Obviously beyond the scope of this Simulator to emulate a Blinks actual memory content beyond allocated data structures. Still an interesting failure mode though.

**Comment by xyfeng** [comment]
Interesting effects, probably caused by shader load stuff from the memory.  I added some code to check undefined colors and set the lights off.
