### ISSUE TITLE
buttonLongPressed needs to clear its flag at the end of a frame?

### ISSUE THREAD

**Issue by gabrieljones** [Move38/Blinks-Simulator#17]
https://github.com/Move38/Blinks-Simulator/blob/6331f75e61d32dbf9f5e55d9efd4c6818c689d1f/examples/js/blink.js#L215-L223

**Comment by gabrieljones** [comment]
https://github.com/Move38/Blinks-Simulator/commit/1c2cb8f42532ad0c72418e13650414b168b7d725 removed the original flag clear to fix Mortals

Maybe flag clearing for all press events needs to be done at the end of a frame?

**Comment by gabrieljones** [comment]
```C++
byte color = 0;

Color colors[7] = {RED, BLUE, GREEN, YELLOW, ORANGE, CYAN, MAGENTA};

void setup() {
}

void loop() {
  if (buttonLongPressed()) color = (color + 1) % 7;
  setColor(colors[color]); 
}
```

**Comment by xyfeng** [comment]
I reversed the code of _buttonLongPressedFlag, Mortals example looks like fine. I think we can keep the flags as it is instead of reset at the end of a frame. @jbobrow, if you have any suggestions what we should do here, let me know.
