### ISSUE TITLE
demo not updating with new template

### ISSUE THREAD

**Issue by hunterpp** [Move38/Blinks-Simulator#20]
I updated template.ino last night with instructions, but they are not reflected in demo https://move38.github.io/Blinks-Simulator/

I am not contributor, is visibility of demo repo not avail to me? https://docs.github.com/en/github/working-with-github-pages/creating-a-github-pages-site

**Comment by xyfeng** [comment]
Ah, it’s in a branch here: https://github.com/Move38/Blinks-Simulator/tree/gh-pages

No need to make another PR, I will copy it over. 

-xy
