### ISSUE TITLE
Uninitialized values for getLastValueReceivedOnFace are -1

### ISSUE THREAD

**Issue by aaronsantiago** [Move38/Blinks-Simulator#22]
Reproduction code: 
```
void loop() {
    FOREACH_FACE(f) { //check every face
      console.log(f + " " + getLastValueReceivedOnFace(f));
        if (isValueReceivedOnFaceExpired(f)) { //no one there
            setColorOnFace(BLUE, f);
        } else { //someone there
            setColorOnFace(WHITE, f);
        }
    }
}
```

This causes some disparities with hardware, where the type of the value returned is always positive.

**Comment by xyfeng** [comment]
fixed, see [here](https://github.com/Move38/Blinks-Simulator/commit/97a716000dc35a99be40b9b336785eecd9385d56#)
base on the [API](https://github.com/Move38/Blinks-SDK/blob/2fd2e45e02ffd8c4ac6468d7cb420dcd29306c9f/cores/blinklib/blinklib.h#L44), return value will be >= 0.
