### ISSUE TITLE
Connecting groups of blinks can delete blinks

### ISSUE THREAD

**Issue by aaronsantiago** [Move38/Blinks-Simulator#24]
![image](https://user-images.githubusercontent.com/47049060/106843351-d8d45b80-6673-11eb-9308-9852364ec3e2.png)

It seems like it happens if one of the groups surrounds the other

**Comment by xyfeng** [comment]
Saw it sometimes, if you know the steps to reproduce, please let me know. thanks.

**Comment by aaronsantiago** [comment]
The picture above is an easy way to reproduce.

- Set the number of Blinks to 12
- Cut out 4 Blinks like pictured
- Drag the bottom left blink and attempt to attach it to the original spot

Some notes--the group of 4 seems to need to be still relatively horizontally aligned, and you need to try dragging into the spot from the bottom.

**Comment by xyfeng** [comment]
Thanks for the steps, the bug should be fixed now. What happened is when groups are joining, it rotated too much and ended up overlapping with another one.
