### ISSUE TITLE
Odd timer behavior

### ISSUE THREAD

**Issue by aaronsantiago** [Move38/Blinks-Simulator#27]
If you use the timer example in the simulator--the saturation timer seems to be totally ignored. What it feels like is that it's on a global timer rather than being reset when the code is rerun--quickly opening the timer example after refreshing the page shows red but every subsequent run of the code seems not to do much.

It's hard to tell how this affects timers in general but the timer example is an easy way to see this happening.

**Comment by xyfeng** [comment]
Good catch, looks like the millis() was not properly reset after code is updated, should be fixed now.
