### ISSUE TITLE
Request to add a license to your project

### ISSUE THREAD

**Issue by Linesmerrill** [Move38/Blinks-Simulator#32]
Hi, I am familiar with your project and I noticed that it does not have a LICENSE file in the root directory. I would like to suggest that you add a license to your project so it can be freely used, modified, repurposed, or shared by the open source community. You can find information on various licenses [here](https://opensource.org/licenses). To choose the right license for your project, check out [choosealicense.com](https://choosealicense.com/). If you have already chosen a license, to apply this license in a way that the community can recognize, you can add a file in the root directory of your default branch named LICENSE containing your license.

**Comment by jbobrow** [comment]
Hi @Linesmerrill, thanks for writing and pointing this out. It is an oversight and we’ll update with the open-source license for this project. This simulator exists because of the incredible effort of @xyfeng and his time at https://www.recurse.com/.

**Comment by Linesmerrill** [comment]
Awesome work! Thank you for the quick reply!

**Comment by jbobrow** [comment]
Missed my opportunity to close the issue with the MIT License commit…🥈

**Comment by Linesmerrill** [comment]
hahah I always forget to do that as well 🤣  thanks again! Cheers
