### ISSUE TITLE
Touch events for use on touch screens

### ISSUE THREAD

**Issue by jbobrow** [Move38/Blinks-Simulator#7]
The drawing to split clusters works by default but the button down and dragging functions are not registering. Adding a touch handler in the same way as the mouse handler should make the app responsive. Additionally, handling multi-touch to move multiple pieces at once could be quick to support by iterating through the multi touch events.

**Comment by xyfeng** [comment]
I see, I didn't test it on touch screens, I will do some debugging.

**Comment by xyfeng** [comment]
I'm currently using MatterJS mouse events to handle dragging each blinks, looks like they are not supporting multitouch events on touch screens, which was discussed here: https://github.com/liabru/matter-js/issues/290

If we implement our own touch events, we will lose all the physics feature that currently applying on each blink while dragging. So this won't be a quick change. I have fixed other issues, will be included in next PR
